"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Shape_1 = require("./Shape");
var Circle_1 = require("./Circle");
var Rectangle_1 = require("./Rectangle");
var shape = new Shape_1.Shape(1, 2);
var circle = new Circle_1.Circle(1, 2, 3);
var rectangle = new Rectangle_1.Rectangle(1, 2, 3, 4);
console.log(shape.getInfo());
console.log(circle.getInfo());
console.log(rectangle.getInfo());
